# Generated by Django 3.2.5 on 2021-11-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=264)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(choices=[('QB', 'Qb'), ('WR', 'Wr'), ('RB', 'Rb'), ('TE', 'Te'), ('Pick', 'Pick')], default='QB', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='User_Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.ManyToManyField(to='analyzer_main.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=25, null=True)),
                ('league_id', models.CharField(max_length=25)),
                ('team_name', models.CharField(max_length=25)),
                ('draft_order', models.CharField(choices=[('Max Points For', 'Max Points For'), ('Standings', 'Standings')], default='Max Points For', max_length=264)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_ranking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer_main.user_ranking')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer_main.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_ranking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer_main.user_ranking')),
            ],
        ),
    ]
