# Generated by Django 3.2.5 on 2021-12-07 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0003_ranking_date_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='date_last_updated',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user_ranking',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
