# Generated by Django 3.2.5 on 2022-01-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0004_auto_20211207_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_ids',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
