# Generated by Django 3.2.5 on 2022-01-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0005_team_team_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_League',
        ),
        migrations.DeleteModel(
            name='My_Team',
        ),
    ]
