# Generated by Django 3.2.5 on 2022-02-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0008_league_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_league_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(max_length=30, null=True)),
                ('vals', models.FloatField(default=0, null=True)),
            ],
            options={
                'db_table': 'league_totalval_table',
            },
        ),
    ]
