# Generated by Django 3.2.5 on 2022-02-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0009_table_league_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_league_total',
            old_name='teams',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='table_league_total',
            old_name='vals',
            new_name='value',
        ),
    ]
