# Generated by Django 3.2.5 on 2022-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0010_auto_20220203_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_output',
            name='league_id',
            field=models.CharField(default='650166753011249152', max_length=30),
            preserve_default=False,
        ),
    ]
