# Generated by Django 3.2.5 on 2022-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0011_league_output_league_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_league_total',
            name='league_id',
            field=models.CharField(default='650166753011249152', max_length=30),
            preserve_default=False,
        ),
    ]
