# Generated by Django 3.2.5 on 2022-02-12 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0014_auto_20220209_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer_main.ranking')),
            ],
        ),
    ]
