# Generated by Django 3.2.5 on 2022-03-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0015_ranking_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_output',
            name='date_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
