# Generated by Django 3.2.5 on 2022-04-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0016_alter_league_output_date_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_output',
            name='id',
        ),
        migrations.RemoveField(
            model_name='table_league_total',
            name='id',
        ),
        migrations.AddField(
            model_name='league_output',
            name='primary_id',
            field=models.CharField(default=None, max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='table_league_total',
            name='primary_id',
            field=models.CharField(default=None, max_length=250, primary_key=True, serialize=False),
        ),
    ]
