# Generated by Django 3.2.5 on 2022-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0017_auto_20220401_2245'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('league_id', 'user'), name='duplicate league'),
        ),
    ]
