# Generated by Django 3.2.5 on 2022-04-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0018_league_duplicate league'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user_ranking',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='duplicate ranking name'),
        ),
    ]
