# Generated by Django 3.2.5 on 2022-10-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_main', '0020_alter_user_ranking_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
